# Generated by Django 6.0.4 on 2026-04-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_created_at_job_description_job_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
