# Generated by Django 5.2.6 on 2026-05-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientrequest_client_alter_clientrequest_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
