# Generated by Django 3.2.25 on 2026-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Electrician', 'Electrician'), ('Client', 'Client')], max_length=20),
        ),
    ]
